# .github/workflows/release.yml

name: Build & Release Electron App

on:
  release:
    types: [created]

# This is the new section that grants the workflow permission to upload files to your release.
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        # This step will build the app and, with the added permissions,
        # will now be able to successfully publish it to the release.
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}