# .github/workflows/release.yml

name: Build & Release Electron App

on:
  release:
    types: [created]

# This grants the workflow permission to upload files to your release.
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        # We add '--publish never' to prevent electron-builder from trying to publish.
        # The upload will be handled by a separate, more reliable step.
        run: npm run dist -- --publish never

      - name: Upload Release Assets
        # This action will find the built installers in the 'dist' folder
        # and upload them to the GitHub release that triggered this workflow.
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true